import { useState, useEffect, useRef } from 'react'
import { authFetch, API_BASE } from '../lib/api'
import { downloadTimeBlocksICS } from '../utils/calendar'
import './ProactivePlan.css'

const DISMISS_KEY = 'campus-ai-plan-dismissed'

const COURSE_COLORS = [
  '#6366f1', '#0ea5e9', '#10b981', '#f59e0b',
  '#ef4444', '#8b5cf6', '#ec4899', '#14b8a6',
]

function getCourseColor(name) {
  if (!name) return COURSE_COLORS[0]
  const h = [...name].reduce((a, c) => a + c.charCodeAt(0), 0)
  return COURSE_COLORS[h % COURSE_COLORS.length]
}

function getMtDateStr(d) {
  const p = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Denver', year: 'numeric', month: '2-digit', day: '2-digit',
  }).formatToParts(d)
  return `${p.find(x => x.type === 'year').value}-${p.find(x => x.type === 'month').value}-${p.find(x => x.type === 'day').value}`
}

function formatBlockTime(isoStr) {
  return new Date(isoStr).toLocaleString('en-US', {
    timeZone: 'America/Denver', hour: 'numeric', minute: '2-digit', hour12: true,
  })
}

function blockDuration(startIso, endIso) {
  const mins = Math.round((new Date(endIso) - new Date(startIso)) / 60000)
  const h = Math.floor(mins / 60)
  const m = mins % 60
  if (h && m) return `${h}h ${m}m`
  if (h) return `${h}h`
  return `${m}m`
}

/**
 * TodayPlanPreview — replaces the old ProactivePlan card.
 *
 * Shows the actual AI-generated time blocks for today (from the time_blocks
 * table via GET /schedule/week). If no blocks exist, prompts the user to
 * generate a plan. Always offers "Chat to adjust".
 */
export default function ProactivePlan({
  involvementLevel,
  onOpenChat,
  addToast,
  refreshKey = 0,
  onBlocksLoaded,
}) {
  const [blocks, setBlocks] = useState(null)   // null = loading, [] = empty
  const [generating, setGenerating] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [dismissed, setDismissed] = useState(() => {
    try { return localStorage.getItem(DISMISS_KEY) === new Date().toDateString() }
    catch { return false }
  })
  const hasFetched = useRef(false)

  const todayStr = getMtDateStr(new Date())

  const fetchTodayBlocks = async () => {
    try {
      const res = await authFetch(`${API_BASE}/schedule/week`)
      if (res.ok) {
        const data = await res.json()
        const todayBlocks = (data.blocks || [])
          .filter(b => b.date === todayStr)
          .sort((a, b) => new Date(a.start_time) - new Date(b.start_time))
        setBlocks(todayBlocks)
        onBlocksLoaded?.(todayBlocks.length)
      } else {
        setBlocks([])
        onBlocksLoaded?.(0)
      }
    } catch {
      setBlocks([])
    }
  }

  // Fetch on mount and whenever refreshKey changes (e.g. after chat apply-plan)
  useEffect(() => {
    hasFetched.current = true
    fetchTodayBlocks()
  }, [refreshKey]) // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-generate for proactive users if no blocks exist yet
  const hasAutoGenerated = useRef(false)
  useEffect(() => {
    if (involvementLevel !== 'proactive') return
    if (hasAutoGenerated.current) return
    if (blocks === null) return  // still loading
    if (blocks.length > 0) return
    if (dismissed) return
    hasAutoGenerated.current = true
    handleGenerate()
  }, [involvementLevel, blocks, dismissed]) // eslint-disable-line react-hooks/exhaustive-deps

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const res = await authFetch(`${API_BASE}/schedule/generate`, { method: 'POST' })
      if (res.ok) {
        addToast('AI plan generated!', 'success')
        await fetchTodayBlocks()
      } else {
        let detail = 'Failed to generate plan.'
        try { const d = await res.json(); detail = d.detail || detail } catch { /**/ }
        addToast(detail, 'error')
      }
    } catch {
      addToast('Failed to generate plan.', 'error')
    } finally {
      setGenerating(false)
    }
  }

  const handleExport = async () => {
    if (exporting) return
    setExporting(true)
    try {
      const res = await authFetch(`${API_BASE}/schedule/week`)
      if (res.ok) {
        const data = await res.json()
        const allBlocks = data.blocks || []
        if (allBlocks.length === 0) {
          addToast?.('No scheduled blocks to export.', 'error')
          return
        }
        downloadTimeBlocksICS(allBlocks, data.week_start)
      } else {
        addToast?.('Could not load schedule for export.', 'error')
      }
    } catch {
      addToast?.('Export failed. Try again.', 'error')
    } finally {
      setExporting(false)
    }
  }

  const dismiss = () => {
    setDismissed(true)
    try { localStorage.setItem(DISMISS_KEY, new Date().toDateString()) } catch { /**/ }
  }

  if (involvementLevel === 'prompt_only') return null
  if (dismissed) return null

  const isLoading = blocks === null || generating
  const hasBlocks = blocks && blocks.length > 0

  // Count remaining (not completed/skipped)
  const remaining = hasBlocks
    ? blocks.filter(b => !['completed', 'skipped'].includes(b.status)).length
    : 0

  return (
    <div className="proactive-card">
      {/* Header */}
      <div className="proactive-header">
        <div className="proactive-title-row">
          <span className="proactive-badge">AI</span>
          <span className="proactive-title">Today&apos;s plan</span>
          {hasBlocks && !isLoading && (
            <span className="proactive-remaining">
              {remaining} block{remaining !== 1 ? 's' : ''} left
            </span>
          )}
        </div>
        <button className="proactive-dismiss" onClick={dismiss} aria-label="Dismiss">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>

      {/* Loading */}
      {isLoading && (
        <div className="proactive-generating">
          <span className="proactive-spinner" />
          <span>{generating ? 'Generating your plan…' : 'Loading schedule…'}</span>
        </div>
      )}

      {/* Time block list */}
      {!isLoading && hasBlocks && (
        <ul className="proactive-list">
          {blocks.map(block => {
            const asgn = block.assignments || {}
            const color = getCourseColor(asgn.course_name)
            const label = block.label || asgn.title || 'Study block'
            const isDone = block.status === 'completed'
            const isSkipped = block.status === 'skipped'
            const dur = blockDuration(block.start_time, block.end_time)

            return (
              <li
                key={block.id}
                className={`proactive-item ${isDone ? 'is-done' : ''} ${isSkipped ? 'is-skipped' : ''}`}
              >
                <div className="proactive-item-accent" style={{ background: color }} />
                <div className="proactive-item-body">
                  <div className="proactive-item-time">
                    {formatBlockTime(block.start_time)}
                    <span className="proactive-item-sep">–</span>
                    {formatBlockTime(block.end_time)}
                    <span className="proactive-item-dur">{dur}</span>
                  </div>
                  <div className="proactive-item-title">{label}</div>
                  {asgn.course_name && (
                    <div className="proactive-item-course">{asgn.course_name}</div>
                  )}
                </div>
                {(isDone || isSkipped) && (
                  <span className={`proactive-status-badge ${isDone ? 'done' : 'skipped'}`}>
                    {isDone ? '✓' : '→'}
                  </span>
                )}
              </li>
            )
          })}
        </ul>
      )}

      {/* Empty state */}
      {!isLoading && !hasBlocks && (
        <div className="proactive-empty">
          <p className="proactive-empty-text">No study blocks scheduled for today.</p>
          <p className="proactive-empty-hint">
            Set time estimates on your assignments, then generate a plan.
          </p>
        </div>
      )}

      {/* Actions */}
      {!isLoading && (
        <div className="proactive-actions">
          {!hasBlocks && (
            <button
              className="proactive-apply"
              onClick={handleGenerate}
              disabled={generating}
            >
              Generate plan
            </button>
          )}
          <button
            className="proactive-chat"
            onClick={() => { onOpenChat?.(); dismiss() }}
          >
            {hasBlocks ? 'Chat to adjust' : 'Ask AI instead'}
          </button>
          {hasBlocks && (
            <div className="proactive-icon-group">
              <button
                className="proactive-icon-btn"
                onClick={handleExport}
                disabled={exporting}
                title="Export week to calendar (.ics)"
                aria-label="Export week to calendar"
              >
                {exporting ? (
                  <span className="proactive-spinner" />
                ) : (
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" y1="15" x2="12" y2="3" />
                  </svg>
                )}
              </button>
              <button
                className="proactive-icon-btn"
                onClick={handleGenerate}
                disabled={generating}
                title="Regenerate plan"
                aria-label="Regenerate plan"
              >
                ↺
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
